openapi: 3.1.0
info:
  title: ASM common schemas
  version: 2025-03

components:
  schemas:
    QuantityValue:
      type: object
      properties:
        value:
          type: number
          format: double
        unit:
          type: string
      required:
        - unit
        - value

    MetersQuantityValue:
      allOf:
        - $ref: '#/components/schemas/QuantityValue'
        - type: object
          properties:
            unit:
              type: string
              enum: ["m"]

    MillimetersQuantityValue:
      allOf:
        - $ref: '#/components/schemas/QuantityValue'
        - type: object
          properties:
            unit:
              type: string
              enum: ["mm"]
    MicrometersQuantityValue:
      allOf:
        - $ref: '#/components/schemas/QuantityValue'
        - type: object
          properties:
            unit:
              type: string
              enum: ["µm"]

    SecondsQuantityValue:
      allOf:
        - $ref: '#/components/schemas/QuantityValue'
        - type: object
          properties:
            unit:
              type: string
              enum: ["s"]

    MicrolitersQuantityValue:
      allOf:
        - $ref: '#/components/schemas/QuantityValue'
        - type: object
          properties:
            unit:
              type: string
              enum: [ "μL" ]
              x-enum-varnames: [ Micro_L ]
              x-enum-values: [ "\u03BCL" ]

    HertzQuantityValue:
      allOf:
        - $ref: '#/components/schemas/QuantityValue'
        - type: object
          properties:
            unit:
              type: string
              enum: [ "Hz" ]

    UnitlessQuantityValue:
      allOf:
        - $ref: '#/components/schemas/QuantityValue'
        - type: object
          properties:
            unit:
              type: string
              enum: [ "(unitless)" ]

    PercentQuantityValue:
      allOf:
        - $ref: '#/components/schemas/QuantityValue'
        - type: object
          properties:
            unit:
              type: string
              enum: [ "%" ]